### ISSUE TITLE
Info to users about recurring reboots

### ISSUE THREAD

**Issue by t-pi** [ecocurious2/MultiGeiger#352] opened 2020-08-05 20:21 UTC
In the Slack, there's currently a discussion about (among other topics) the reboots with a (non-developer) user. It would be good to mention the current recurring reboots in our documentation about V1.14, wouldn't it?

**Comment by M-a-r-i-a-n-n-e** [comment] 2021-03-20 13:44
@ThomasWaldmann  @WwwBoehriDe Is there already a workaround or a fix for this issue?

**Comment by ThomasWaldmann** [comment] 2021-03-20 16:56
In the last BBB meeting, we noticed that there is arduino-esp32 1.05 out now since ~3 weeks.

Maybe they fixed the problem in the updated HTTPClient code.

**Comment by M-a-r-i-a-n-n-e** [comment] 2021-03-20 17:16
I don't think so, as I already compiled it with framework-arduinoespressif32 3.10005.210308 (1.0.5) cf. https://github.com/espressif/arduino-esp32/releases

**Comment by M-a-r-i-a-n-n-e** [comment] 2021-03-20 18:00
Is there any workaround? Is the root cause already known?

**Comment by ThomasWaldmann** [comment] 2021-03-20 18:51
See #314. This issue is just about writing some docs, notifying the users - not about the crash and its root cause.

**Comment by ThomasWaldmann** [comment] 2021-03-20 19:09
I thought about this. If a user encounters an issue, expectation is that the issue tracker on github is checked whether the issue is known (which is the case here, see #314) and if not, file a new issue.

Thus, there is nothing to do here.

**Closed by ThomasWaldmann** 2021-03-20 19:09 UTC

**Comment by M-a-r-i-a-n-n-e** [comment] 2021-03-20 21:56
@ThomasWaldmann You think that a defect that leads to a restart every second is unworthy of a line in the documentation? Interesting.

**Comment by ThomasWaldmann** [comment] 2021-03-21 01:03
I don't have restarts every second.

**Comment by ThomasWaldmann** [comment] 2021-03-21 01:09
@M-a-r-i-a-n-n-e maybe you(?) have a different issue - then we need a new github issue with tracebacks similar to the ones you see in #314 (IF they are different from the ones in #314).

**Comment by M-a-r-i-a-n-n-e** [comment] 2021-03-21 08:44
> @M-a-r-i-a-n-n-e maybe you(?) have a different issue - then we need a new github issue with tracebacks similar to the ones you see in #314 (IF they are different from the ones in #314).

Yes, unfortunately this seems to be the case, although I just followed the simple steps in https://multigeiger.readthedocs.io/en/latest/development.html#flashing-devices-creating-binaries (and of course installed the libraries using the library manager).

**Comment by ThomasWaldmann** [comment] 2021-03-21 20:00
@M-a-r-i-a-n-n-e try that: https://github.com/ecocurious2/MultiGeiger/releases/tag/V1.15.0

**Comment by M-a-r-i-a-n-n-e** [comment] 2021-03-21 20:38
@ThomasWaldmann Thank you for the new release! It first hurt my ears, because as long as I didn't erase the ESP32 memory it beeps at full volume, but after erasing the memory with the ESP32 Download Tool, it runs like a charm! 🙂👍
